# Here is the test snapshot on python IDE
When we ran find_value.py

![picture alt](https://github.com/priyal-agrawal/Tech_Challenges/blob/21b1dda28c53da87258e2ae696b6d36df19c94b3/Challenge%203/test/test.jpg)

When unit Test ran successfully
```
$ python unitTest.py
Everything passed
```
